name: "Lint Checks"
on:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required for new-from-rev option in .golangci.yml
      - name: Install specific golang
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Check format
        run: test -z `go fmt ./...`
      - name: Vet
        run: go vet ./...
      - name: reviewdog-golangci-lint
        uses: reviewdog/action-golangci-lint@v2.8
        with:
          golangci_lint_version: "v2.5.0"
          golangci_lint_flags: "-c .golangci.yml --allow-parallel-runners"
          go_version_file: "go.mod"
          reporter: "github-pr-review"
          tool_name: "Lint Errors"
          level: "error"
          fail_on_error: true
          filter_mode: "nofilter"